services:
    db:
        image: postgres:15-alpine
        restart: always
        ports:
            - '127.0.0.1:5432:5432'  # Expose PostgreSQL uniquement en local
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - db-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 5s

    api:
        build: ./back
        environment:
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
            JWT_SECRET: ${JWT_SECRET}
            JWT_SECRET_ADMIN: ${JWT_SECRET_ADMIN}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - opal-network
            - db-network

    front:
        build: ./front
        restart: always
        networks:
            - opal-network

    reverse-proxy:
        image: nginx:latest
        ports:
            - '80:80'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - front
            - api
        networks:
            - opal-network

networks:
    opal-network:
    db-network:

volumes:
    postgres_data:
